In [1]:
dir_root = '.'
# If using google colab
if 'google.colab' in str(get_ipython()):
    from google.colab import drive
    drive.mount('/content/drive/')
    dir_root = '/content/drive/MyDrive/Colab Notebooks/ESE546/hw3'

print(dir_root)

.


In [2]:
import requests

# Load the text from a local file
def load_text_from_file(file_path):
    with open(file_path, 'r', encoding='utf-8') as file:
        text = file.read()
    return text

# Load the text from a URL
def load_text_from_url(url):
    response = requests.get(url)
    text = response.text.replace('\r\n', '\n')  # Normalize line endings
    return text

# Count unique characters in the text
def count_unique_chars(text):
    unique_chars = set(text)
    # Num of unique characters
    vocab_size = len(unique_chars)
    return vocab_size, unique_chars

# List of file paths or URLs
local_file_1 = 'pg100.txt'
local_file_2 = 'pg2600.txt'
local_file_3 = 'pg766.txt'
url_file_1 = 'https://www.gutenberg.org/cache/epub/100/pg100.txt'
url_file_2 = 'https://www.gutenberg.org/cache/epub/2600/pg2600.txt'
url_file_3 = 'https://www.gutenberg.org/cache/epub/766/pg766.txt'

if 'google.colab' in str(get_ipython()):
    file_path_list = [url_file_1, url_file_2, url_file_3]
else:
    file_path_list = [local_file_1, local_file_2, local_file_3]
text_list = []
vocab_size_list = []
unique_chars_list = []

for file_path in file_path_list:
    if file_path.startswith('http'):
        print(f'Loading text from URL: {file_path}')
        text = load_text_from_url(file_path)
    else:
        print(f'Loading text from file: {file_path}')
        text = load_text_from_file(file_path)
    vocab_size, unique_chars = count_unique_chars(text)
    text_list.append(text)
    vocab_size_list.append(vocab_size)
    unique_chars_list.append(unique_chars)

print(f'Vocabulary size for each text: {vocab_size_list}')
print(f'Unique characters for each text: {unique_chars_list}')
print(f'Example unique characters: {unique_chars_list[0]}')

Loading text from file: pg100.txt
Loading text from file: pg2600.txt
Loading text from file: pg766.txt
Vocabulary size for each text: [107, 112, 90]
Unique characters for each text: [{'L', 'T', ']', 'é', '6', 'e', 'l', 'N', 'v', 'Z', 'H', '-', 'ê', '“', 'o', '1', '8', '”', '[', 'b', 'O', '*', 'J', '7', '/', 'É', '9', '’', 'æ', ' ', 'P', 'W', '_', 'À', '$', 'E', 'r', 't', '?', 'ç', '•', 'A', '—', 'â', '&', 'G', 'R', 'S', '4', 'k', 'j', 'u', 'ë', ',', '0', 'Ç', '#', 'p', '.', ')', 'è', 'I', 'g', 'y', 'œ', 'B', 'à', 'h', '\ufeff', ';', 'Q', '3', 'î', '%', 'Æ', '(', 'w', '\n', 'Y', '‘', 'a', 'n', '2', 'x', 'm', 's', '5', 'i', 'M', 'F', 'K', ':', 'd', 'c', 'f', "'", 'X', 'q', 'D', '!', '™', 'C', '\t', '…', 'z', 'V', 'U'}, {'L', 'T', ']', 'é', '6', 'e', 'l', 'N', '=', 'v', 'ó', 'Z', 'H', '-', 'ê', '“', 'o', '1', '8', '”', '[', 'b', 'O', '*', 'ú', 'J', '7', '/', 'ö', 'É', '9', '’', 'æ', ' ', 'P', 'W', 'À', '$', 'E', 'r', 't', '?', 'ç', 'ï', '•', 'A', '—', 'ý', 'â', 'Á', 'G', 'R', 'S', 'ü', '4

In [3]:
# # Compare unique characters from local and URL text files
# local_file_path = 'pg2600.txt'
# url_file_path = 'https://www.gutenberg.org/cache/epub/2600/pg2600.txt'
#
# local_text = load_text_from_file(local_file_path)
# local_vocab_size, local_unique_chars = count_unique_chars(local_text)
# url_text = load_text_from_url(url_file_path)
# url_vocab_size, url_unique_chars = count_unique_chars(url_text)
#
# # Find the extra character(s)
# extra_chars_in_url = url_unique_chars - local_unique_chars
# extra_chars_in_local = local_unique_chars - url_unique_chars
# print(f'Extra characters in URL text: {extra_chars_in_url}')
# print(f'Extra characters in local text: {extra_chars_in_local}')

In [4]:
# Create a dictionary to map characters to indices and vice-versa
def create_char_mappings(unique_chars):
    char_to_index = {char: idx for idx, char in enumerate(unique_chars)}
    index_to_char = {idx: char for idx, char in enumerate(unique_chars)}
    return char_to_index, index_to_char

vocab_size, unique_chars = vocab_size_list[0], unique_chars_list[0]
char_to_index, index_to_char = create_char_mappings(unique_chars)

print(f"Character to index mapping for first text: {char_to_index}")
print(f"Index to character mapping for first text: {index_to_char}")

Character to index mapping for first text: {'L': 0, 'T': 1, ']': 2, 'é': 3, '6': 4, 'e': 5, 'l': 6, 'N': 7, 'v': 8, 'Z': 9, 'H': 10, '-': 11, 'ê': 12, '“': 13, 'o': 14, '1': 15, '8': 16, '”': 17, '[': 18, 'b': 19, 'O': 20, '*': 21, 'J': 22, '7': 23, '/': 24, 'É': 25, '9': 26, '’': 27, 'æ': 28, ' ': 29, 'P': 30, 'W': 31, '_': 32, 'À': 33, '$': 34, 'E': 35, 'r': 36, 't': 37, '?': 38, 'ç': 39, '•': 40, 'A': 41, '—': 42, 'â': 43, '&': 44, 'G': 45, 'R': 46, 'S': 47, '4': 48, 'k': 49, 'j': 50, 'u': 51, 'ë': 52, ',': 53, '0': 54, 'Ç': 55, '#': 56, 'p': 57, '.': 58, ')': 59, 'è': 60, 'I': 61, 'g': 62, 'y': 63, 'œ': 64, 'B': 65, 'à': 66, 'h': 67, '\ufeff': 68, ';': 69, 'Q': 70, '3': 71, 'î': 72, '%': 73, 'Æ': 74, '(': 75, 'w': 76, '\n': 77, 'Y': 78, '‘': 79, 'a': 80, 'n': 81, '2': 82, 'x': 83, 'm': 84, 's': 85, '5': 86, 'i': 87, 'M': 88, 'F': 89, 'K': 90, ':': 91, 'd': 92, 'c': 93, 'f': 94, "'": 95, 'X': 96, 'q': 97, 'D': 98, '!': 99, '™': 100, 'C': 101, '\t': 102, '…': 103, 'z': 104, 'V': 105,

In [5]:
import numpy as np

# One-hot encode a character based on the character index
def one_hot_encode(char, char_to_index, vocab_size):
    one_hot_vector = np.zeros(vocab_size)
    one_hot_vector[char_to_index[char]] = 1
    return one_hot_vector

test_char_a = 'a'
one_hot_vector = one_hot_encode(test_char_a, char_to_index, vocab_size)
print(f"One-hot encoding for '{test_char_a}': {one_hot_vector}")

One-hot encoding for 'a': [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
# Sample a short portion from the first book
text = text_list[0][60000:61000]
print(text)

 ill:
Some in their hawks and hounds, some in their horse.
And every humour hath his adjunct pleasure,
Wherein it finds a joy above the rest,
But these particulars are not my measure,
All these I better in one general best.
Thy love is better than high birth to me,
Richer than wealth, prouder than garments’ costs,
Of more delight than hawks and horses be:
And having thee, of all men’s pride I boast.
  Wretched in this alone, that thou mayst take,
  All this away, and me most wretched make.


                    92

But do thy worst to steal thyself away,
For term of life thou art assured mine,
And life no longer than thy love will stay,
For it depends upon that love of thine.
Then need I not to fear the worst of wrongs,
When in the least of them my life hath end,
I see, a better state to me belongs
Than that, which on thy humour doth depend.
Thou canst not vex me with inconstant mind,
Since that my life on thy revolt doth lie,
O what a happy title do I find,
Happy to have thy love, hap

In [7]:
from tqdm import tqdm

# Generate sequences of 32 characters and the next character as the target
def generate_sequences(text, char_to_index, sequence_length=32, stride=1):
    input_sequences = []
    target_characters = []

    # for i in range(0, len(text) - sequence_length, stride):
    for i in tqdm(range(0, len(text) - sequence_length - 1, stride), desc="Generating sequences"):
        input_seq = text[i:i+sequence_length]
        # Target/next character
        target_char = text[i+sequence_length]

        # Convert input sequence to one-hot encoded vectors
        input_seq_encoded = [one_hot_encode(c, char_to_index, len(char_to_index)) for c in input_seq]
        input_sequences.append(input_seq_encoded)

        # One-hot encoding for the target character
        target_char_encoded = one_hot_encode(target_char, char_to_index, len(char_to_index))
        target_characters.append(target_char_encoded)

    return np.array(input_sequences), np.array(target_characters)


In [8]:
input_sequences, target_characters = generate_sequences(text, char_to_index)
print(f"Input sequences shape: {input_sequences.shape}")
print(f"Target characters shape: {target_characters.shape}")
print(input_sequences[2])
print(target_characters[35])

Generating sequences:   0%|          | 0/967 [00:00<?, ?it/s]

Generating sequences: 100%|██████████| 967/967 [00:00<00:00, 29771.07it/s]

Input sequences shape: (967, 32, 107)
Target characters shape: (967, 107)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [13]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
from torch.utils.data import DataLoader, TensorDataset, random_split
from tqdm import tqdm

if torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")

print(f"Device: {device}")

class CharRNN(nn.Module):
    def __init__(self, vocab_size, hidden_size, dropout=0.2):
        super(CharRNN, self).__init__()
        self.hidden_size = hidden_size
        self.rnn = nn.RNN(vocab_size, self.hidden_size, batch_first=True)
        self.dropout = nn.Dropout(dropout)
        self.fc = nn.Linear(self.hidden_size, vocab_size)

    def forward(self, x, hidden):
        out, hidden = self.rnn(x, hidden)
        out = self.dropout(out)
        out = self.fc(out)
        return F.log_softmax(out, dim=2), hidden
    
    def init_hidden(self, batch_size):
        return torch.zeros(1, batch_size, self.hidden_size).to(device)

def repackage_hidden(hidden_layer):
    # Detach hidden states from their history
    if isinstance(hidden_layer, torch.Tensor):
        return hidden_layer.detach()
    else:
        return tuple(repackage_hidden(v) for v in hidden_layer)


Device: cuda


In [9]:
USE_ALL_BOOKS = False

if 'google.colab' in str(get_ipython()):
    USE_ALL_BOOKS = True

if USE_ALL_BOOKS:
    # Load text and prepare data
    all_texts = ''.join(text_list)  # Concatenate all texts
    vocab_size, unique_chars = count_unique_chars(all_texts)
    char_to_index, index_to_char = create_char_mappings(unique_chars)
    
    # Generate sequences
    input_sequences, target_characters = generate_sequences(all_texts, char_to_index, stride=16)
    input_sequences = torch.tensor(input_sequences, dtype=torch.float32)
    target_characters = torch.tensor(target_characters, dtype=torch.long)
    
    # Create TensorDataset and DataLoader
    dataset = TensorDataset(input_sequences, target_characters)
    train_size = int(0.8 * len(dataset))
    val_size = len(dataset) - train_size
    train_dataset, val_dataset = random_split(dataset, [train_size, val_size])
    
    print("Input sequences shape:", input_sequences.shape)
    print("Target characters shape:", target_characters.shape)
else:
    text = text_list[0]
    vocab_size, unique_chars = vocab_size_list[0], unique_chars_list[0]
    char_to_index, index_to_char = create_char_mappings(unique_chars)
    
    input_sequences, target_characters = generate_sequences(text, char_to_index, stride=64)
    input_sequences = torch.tensor(input_sequences, dtype=torch.float32)
    target_characters = torch.tensor(target_characters, dtype=torch.long)
    
    dataset = TensorDataset(input_sequences, target_characters)
    train_size = int(0.8 * len(dataset))
    val_size = len(dataset) - train_size
    train_dataset, val_dataset = random_split(dataset, [train_size, val_size])
    
    print("Input sequences shape:", input_sequences.shape)
    print("Target characters shape:", target_characters.shape)



Generating sequences: 100%|██████████| 84042/84042 [00:02<00:00, 31995.33it/s]


Input sequences shape: torch.Size([84042, 32, 107])
Target characters shape: torch.Size([84042, 107])


In [26]:
from IPython.display import clear_output
import torch.optim.lr_scheduler as lr_scheduler

# Hyperparameters
hidden_size = 256
learning_rate = 0.01
num_epochs = 10000 if 'google.colab' in str(get_ipython()) else 10
batch_size = 64
dropout = 0.5

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=4)
val_loader = DataLoader(val_dataset, batch_size=batch_size, num_workers=4)

# Initialize model, loss function, and optimizer
model = CharRNN(vocab_size, hidden_size, dropout).to(device)
criterion = nn.NLLLoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)
scheduler = lr_scheduler.ExponentialLR(optimizer, gamma=0.9)  # Adjust gamma as needed

# Training loop
for epoch in tqdm(range(num_epochs), desc="Training"):
    model.train()
    total_loss = 0
    for input_seqs, target_seqs in train_loader:
        batch_size = input_seqs.size(0)
        input_seqs, target_seqs = input_seqs.to(device), target_seqs.to(device)
        hidden = model.init_hidden(batch_size).to(device)
        hidden = repackage_hidden(hidden)
        optimizer.zero_grad()
        output, hidden = model(input_seqs, hidden)
        # print("Output shape:", output.shape)
        # print("Target shape:", target_seqs.shape)
        loss = criterion(output, target_seqs)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    
    if epoch >= 1000:
        scheduler.step()
    
    if epoch % 100 == 0 or epoch >= num_epochs - 1:
        print(f'Epoch {epoch+1}, Training Loss: {total_loss / len(train_loader)}')
    if epoch % 1000 == 0 or epoch >= num_epochs - 1:
        # Validation
        model.eval()
        with torch.no_grad():
            val_loss = 0
            for input_seqs, target_seqs in val_loader:
                batch_size = input_seqs.size(0)
                input_seqs, target_seqs = input_seqs.to(device), target_seqs.to(device)
                hidden = model.init_hidden(batch_size).to(device)
                hidden = repackage_hidden(hidden)
                output, hidden = model(input_seqs, hidden)
                val_loss += criterion(output, target_seqs).item()
        
            print(f'Validation Loss: {val_loss / len(val_loader)}')


Training:   0%|          | 0/10 [00:00<?, ?it/s]

Epoch 1, Training Loss: 4.662619755905544


Training:  10%|█         | 1/10 [00:03<00:33,  3.76s/it]

Validation Loss: 4.661312505772812


Training: 100%|██████████| 10/10 [00:31<00:00,  3.18s/it]


In [33]:
# Save the model
model_path = f'{dir_root}/char_rnn_model.pth'
torch.save(model.state_dict(), model_path)
print(f"Model saved to {model_path}")

Model saved to ./char_rnn_model.pth


In [29]:
# Load the model
model = CharRNN(vocab_size, hidden_size, dropout).to(device)
model.load_state_dict(torch.load(model_path))
model.eval()
print("Model loaded successfully")

Model loaded successfully


C:\Users\Bw Jiang\AppData\Local\Temp\ipykernel_32960\2194315477.py:3: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(model_path))


In [34]:
def generate_text(model, start_text, char_to_index, index_to_char, max_length=1000, temperature=1.0):
    model.eval()
    with torch.no_grad():
        hidden = model.init_hidden(1).to(device)
        hidden = repackage_hidden(hidden)
        input_seq = start_text
        generated_text = start_text

        for i in range(max_length):
            input_seq_encoded = torch.tensor([one_hot_encode(c, char_to_index, len(char_to_index)) for c in input_seq], dtype=torch.float32).unsqueeze(0).to(device)
            output, hidden = model(input_seq_encoded, hidden)
            output_dist = output.data.view(-1).div(temperature).exp()
            top_char = torch.multinomial(output_dist, 1)[0]
            
            # Ensure the predicted index is within the valid range
            if top_char.item() in index_to_char:
                predicted_char = index_to_char[top_char.item()]
            else:
                predicted_char = ''  # Handle out-of-range index by skipping or using a placeholder

            generated_text += predicted_char
            input_seq = input_seq[1:] + predicted_char

    return generated_text

In [36]:
# Generate text using the trained model
start_text = 'The '
generated_text = generate_text(model, start_text, char_to_index, index_to_char, max_length=100, temperature=0.1)
print(generated_text)

The    ‘X!d ”œrbb ilrb eeobrrS  M[-.GGXJ:J72CSæ’’’’’GC[[[S[[[XX.oMM’oUUUCo ”UUUXCCCEHyxneerrytiiRilyt
